# Generated by Django 6.0.1 on 2026-01-10 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_razaosocial', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('perfil_nomefantasia', models.CharField(max_length=30, verbose_name='Nome de Fantasia')),
                ('perfil_cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('perfil_inscest', models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Estadual')),
                ('perfil_inscmun', models.CharField(blank=True, max_length=30, null=True, verbose_name='Incrição Municipal')),
                ('perfil_email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('perfil_endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('perfil_numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('perfil_complemento', models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento')),
                ('perfil_bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('perfil_cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('perfil_cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('perfil_uf', models.CharField(max_length=2, verbose_name='UF')),
                ('perfil_telefone1', models.CharField(max_length=20, verbose_name='Telefone-1')),
                ('perfil_telefone2', models.CharField(max_length=20, verbose_name='Telefone-2')),
                ('perfil_observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('perfil_datafundacao', models.DateField(verbose_name='Data da Fundação')),
                ('perfil_datacadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil(Empresa)',
                'verbose_name_plural': 'Perfis(Empresas)',
            },
        ),
    ]
