# Generated by Django 6.0.1 on 2026-01-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuarioperfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusAssociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusassociacao_descricao', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
        ),
    ]
