# Generated by Django 6.0.1 on 2026-01-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_statusassociacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAssociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoassociado_descricao', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Associado',
                'verbose_name_plural': 'Tipos de Associados',
            },
        ),
        migrations.AlterModelOptions(
            name='statusassociacao',
            options={'verbose_name': 'Status Associação', 'verbose_name_plural': 'Status Associações'},
        ),
    ]
