# Generated by Django 6.0.1 on 2026-01-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tipoassociado_alter_statusassociacao_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoplano_descricao', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Plano',
                'verbose_name_plural': 'Tipos de Planos',
            },
        ),
    ]
