# Generated by Django 6.0.1 on 2026-01-12 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_genero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associado_nome', models.CharField(max_length=100, verbose_name='Nome do Associado')),
                ('associado_email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('associado_telefone', models.CharField(max_length=20, verbose_name='Telefone-2')),
                ('associado_datacadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('associado_observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('associado_codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Interno')),
                ('tipoassociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipoassociado', verbose_name='Tipo Associado')),
                ('tipoplano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipoplano', verbose_name='Tipo do Plano')),
                ('usuarioadm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
