# Generated by Django 6.0.1 on 2026-01-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userclone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclone',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
