# Generated by Django 6.0.1 on 2026-01-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userclone_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='associado_codigo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Código Interno'),
        ),
    ]
