# Generated by Django 6.0.1 on 2026-01-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_associado_associado_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusAssociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Status Associado',
                'verbose_name_plural': 'Status Associados',
            },
        ),
    ]
