# Generated by Django 6.0.1 on 2026-01-17 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_associado_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.statusassociacao', verbose_name='Status Associação'),
        ),
    ]
