# Generated by Django 6.0.1 on 2026-01-18 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_associado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclone',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.statusassociacao', verbose_name='Status da Associação'),
        ),
    ]
