# Generated by Django 6.0.1 on 2026-01-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userclone_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclone',
            name='tri_indica',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
