# Generated by Django 6.0.1 on 2026-01-18 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userclone_tri_indica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociadoPadrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assocpadrinho_datacadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('assocpadrinho_observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('indicado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='padrinhos', to='core.associado')),
                ('padrinho1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padrinho1_de', to='core.associado')),
                ('padrinho2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padrinho2_de', to='core.associado')),
                ('padrinho3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padrinho3_de', to='core.associado')),
                ('usuarioadm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
