# Generated by Django 6.0.1 on 2026-01-19 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_associadoamigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociadoApadrinhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assocapad_datacadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('assocapad_observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('apadrinhado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apadrinhado', to='core.associado')),
                ('padrinho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='padrinho', to='core.associado')),
                ('usuarioadm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
