# Generated by Django 6.0.1 on 2026-01-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_mensagemassociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='associado_uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF do Associado'),
        ),
    ]
