# Generated by Django 6.0.1 on 2026-01-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_timelinepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinepost',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='timeline/imagens/'),
        ),
        migrations.AddField(
            model_name='timelinepost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='timeline/videos/'),
        ),
    ]
