# Generated by Django 6.0.1 on 2026-01-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_associado_usuarioadm'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='associado_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
