# Generated by Django 6.0.1 on 2026-01-22 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_forumresposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopico',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='core.forumcategoria'),
        ),
    ]
