# Generated by Django 6.0.1 on 2026-01-22 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_forumtopico_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcategoria',
            options={'verbose_name': 'Categoria de Forum', 'verbose_name_plural': 'Categorias de Foruns'},
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='postagens/imagens/')),
                ('video', models.FileField(blank=True, null=True, upload_to='postagens/videos/')),
                ('legenda', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('visivel_na_timeline', models.BooleanField(default=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.associado')),
            ],
        ),
    ]
