# Generated by Django 6.0.1 on 2026-01-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_forumcategoria_options_postagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelinepost',
            name='associado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_posts', to='core.associado'),
        ),
    ]
