# Generated by Django 6.0.1 on 2026-01-22 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_timelinecomentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postagem',
        ),
    ]
