# Generated by Django 6.0.1 on 2026-01-22 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_delete_postagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguindo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='core.associado')),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segue', to='core.associado')),
            ],
            options={
                'unique_together': {('seguidor', 'seguido')},
            },
        ),
    ]
