# Generated by Django 6.0.1 on 2026-01-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_timelinepost_ativo_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
