# Generated by Django 6.0.1 on 2026-01-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_delete_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioPerfil',
        ),
    ]
