# Generated by Django 6.0.1 on 2026-01-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_delete_usuarioperfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusAssociado',
        ),
    ]
