# Generated by Django 6.0.1 on 2026-01-24 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresencaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_eventos', to='core.associado')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='core.evento')),
            ],
            options={
                'unique_together': {('associado', 'evento')},
            },
        ),
    ]
