# Generated by Django 6.0.1 on 2026-01-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_presencaevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='midia',
            field=models.FileField(blank=True, null=True, upload_to='eventos/'),
        ),
    ]
