# Generated by Django 6.0.1 on 2026-01-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_grupo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MensagemAssociado',
        ),
    ]
