# Generated by Django 6.0.1 on 2026-01-26 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_delete_mensagemassociado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('participante1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas1', to='core.associado')),
                ('participante2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas2', to='core.associado')),
            ],
            options={
                'unique_together': {('participante1', 'participante2')},
            },
        ),
        migrations.CreateModel(
            name='MensagemAssociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.conversa')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='core.associado')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
