# Generated by Django 6.0.1 on 2026-01-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_conversa_mensagemassociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoplano',
            name='tipoplano_duracao',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='tipoplano',
            name='tipoplano_observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='tipoplano',
            name='tipoplano_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
