# Generated by Django 6.0.1 on 2026-01-26 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_tipoplano_tipoplano_duracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=False)),
                ('pago', models.BooleanField(default=False)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.associado')),
                ('tipoplano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoplano')),
            ],
        ),
    ]
