# Generated by Django 6.0.1 on 2026-01-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='assinada',
            field=models.BooleanField(default=False),
        ),
    ]
