# Generated by Django 6.0.1 on 2026-01-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_assinatura_assinada'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='plano_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
