# Generated by Django 6.0.1 on 2026-01-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_assinatura_plano_confirmado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclone',
            name='status',
        ),
    ]
