# Generated by Django 6.0.1 on 2026-01-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_userclone_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclone',
            name='tipoplano',
        ),
    ]
