# Generated by Django 6.0.1 on 2026-01-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_userclone_tipoplano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclone',
            name='tri_indica',
        ),
    ]
