# Generated by Django 6.0.1 on 2026-01-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_userclone_tri_indica'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='tri_indica',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
