# Generated by Django 6.0.1 on 2026-01-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_associado_tri_indica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='plano_confirmado',
        ),
    ]
