# Generated by Django 6.0.1 on 2026-01-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_remove_assinatura_plano_confirmado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclone',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userclone',
            name='foto',
        ),
    ]
